import { Photo, Track, GallerySection, Playlist, Letter, TimelineEvent } from '@/types';

// Dados das fotos da galeria
export const galleryPhotos: Photo[] = [
  {
    id: '1',
    src: '/images/galeria/11.jpg',
    alt: 'Nosso momento especial',
    caption: 'Com você eu me sinto o cara mais sortudo do mundo, amor 💕',
    date: '2025-05-24',
    location: 'Nosso cantinho especial',
    tags: ['amor', 'momentos-especiais'],
  },
  {
    id: '2',
    src: '/images/galeria/22.jpg',
    alt: 'Juntinhos e felizes',
    caption: 'Você me faz ser o homem mais feliz do mundo ao seu lado ✨',
    date: '2025-03-05',
    location: 'Onde somos felizes',
    tags: ['felicidade', 'espontâneo'],
  },
  {
    id: '3',
    src: '/images/galeria/33.jpg',
    alt: 'Momento de carinho',
    caption: 'Mayanne, eu amo como você fica linda em qualquer foto que a gente tira 🌟',
    date: '2024-12-23',
    location: 'Nossos momentos',
    tags: ['carinho', 'beleza'],
  },
  {
    id: '4',
    src: '/images/galeria/44.jpg',
    alt: 'Sorrisos sinceros',
    caption: 'Meu mundo fica mais colorido quando você está comigo, amor 😊',
    date: '2024-12-25',
    location: 'Sempre felizes',
    tags: ['sorriso', 'radiante'],
  },
  {
    id: '5',
    src: '/images/galeria/55.jpg',
    alt: 'Cumplicidade pura',
    caption: 'Branquela, essa nossa cumplicidade é tudo pra mim 🐋',
    date: '2025-04-19',
    location: 'Nossa conexão',
    tags: ['cumplicidade', 'conexão'],
  },
  {
    id: '6',
    src: '/images/galeria/66.jpg',
    alt: 'Momentos únicos',
    caption: 'Mayanne, você é a protagonista de todos os meus momentos favoritos 📸💕',
    date: '2025-05-03',
    location: 'Construindo memórias',
    tags: ['memórias', 'especial'],
  },
];

// Seção da galeria
export const gallerySections: GallerySection[] = [
  {
    id: 'momentos-especiais',
    title: 'Nossos Momentos Especiais',
    photos: galleryPhotos,
  },
];

// Dados para o carousel da galeria
export const carouselSlides = galleryPhotos.map((photo, index) => {
  const titles = [
    'Você me faz o homem mais feliz do mundo',
    'Com você tudo é mais especial', 
    'Você fica linda em tudo',
    'Meu coração acelera quando te vejo',
    'Nossa conexão é única',
    'Construindo memórias juntos'
  ];

  const descriptions = [
    'Sou completamente apaixonado por você, amor 🍒',
    'Com você tudo fica mais leve e bonito 🤟🏻',
    'Você me enche de orgulho em tudo que faz, meu bem 🌟',
    'Ao seu lado eu me sinto completo e feliz 🤍',
    'Branquela, nossa cumplicidade é tudo pra mim 🐋',
    'Amo cada detalhe em você, nê 🌷'
  ];
  
  return {
    title: titles[index] || 'Memória Especial',
    button: 'Ver Memória',
    src: photo.src,
    description: descriptions[index] || photo.caption,
  };
});

// Playlist de músicas (baseado nos arquivos disponíveis)
export const musicTracks: Track[] = [
  {
    id: '48',
    title: 'Perdoa',
    artist: 'Anavitória',
    album: 'O Tempo É Agora',
    src: '/music/playlist/ANAVITÓRIA - Perdoa.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 210,
    description: 'Um pedido de perdão em forma de canção.',
  },
  {
    id: '37',
    title: 'Quando Bate Aquela Saudade',
    artist: 'Rubel',
    album: 'Pearl',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Quando Bate Aquela Saudade.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Para os momentos de saudade.',
  },
  {
    id: '1',
    title: 'A Cera',
    artist: 'O Surto',
    album: 'Equalize',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] A Cera.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 240,
    description: 'Para nossos momentos de pura energia.',
  },
  {
    id: '2',
    title: 'A Droga do Amor',
    artist: 'Ariah',
    album: 'Single',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] A Droga do Amor.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 270,
    description: 'Quando o amor é a melhor droga.',
  },
  {
    id: '3',
    title: 'Ai Calica',
    artist: 'Ponto de Equilíbrio',
    album: 'Dia Após Dia Lutando',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Ai Calica.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 210,
    description: 'Aquele reggae que nos conecta.',
  },
  {
    id: '4',
    title: 'Ai, Amor',
    artist: 'Anavitória',
    album: 'O Tempo É Agora',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Ai, Amor.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 150,
    description: 'Simplesmente amor.',
  },
  {
    id: '5',
    title: 'Ainda Bem',
    artist: 'Marisa Monte',
    album: 'O Que Você Quer Saber de Verdade',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Ainda Bem.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 180,
    description: 'Ainda bem que te encontrei.',
  },
  {
    id: '6',
    title: 'Aliança',
    artist: 'Tribalistas',
    album: 'Tribalistas',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Aliança.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 200,
    description: 'Nossa aliança de amor.',
  },
  {
    id: '7',
    title: 'Amado',
    artist: 'Vanessa da Mata',
    album: 'Sim',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Amado.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 180,
    description: 'Meu amado, meu amor.',
  },
  {
    id: '8',
    title: 'Amanhecer',
    artist: 'Scalene',
    album: 'Real/Surreal',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Amanhecer.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Para ver o sol nascer ao seu lado.',
  },
  {
    id: '9',
    title: 'Aqueles Olhos',
    artist: 'Dom M',
    album: 'Single',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Aqueles Olhos.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Me perco nesses olhos.',
  },
  {
    id: '10',
    title: 'Can\'t Help Falling in Love',
    artist: 'Elvis Presley',
    album: 'Blue Hawaii',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Can\'t Help Falling in Love.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Não consigo evitar me apaixonar por você.',
  },
  {
    id: '11',
    title: 'Cataflor - Ao Vivo',
    artist: 'Tiago Iorc',
    album: 'Troco Likes Ao Vivo',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Cataflor - Ao Vivo.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Como uma flor para você.',
  },
  {
    id: '12',
    title: 'Céu Azul',
    artist: 'Charlie Brown Jr.',
    album: 'Música Popular Caiçara',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Céu Azul.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Tão natural quanto a luz do dia.',
  },
  {
    id: '13',
    title: 'Cheiro De Amor',
    artist: 'Maria Bethânia',
    album: 'As Canções Que Você Fez Pra Mim',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Cheiro De Amor.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'O cheiro do nosso amor no ar.',
  },
  {
    id: '14',
    title: 'Cor De Marte',
    artist: 'Anavitória',
    album: 'Anavitória',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Cor De Marte.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Nosso amor com a cor de Marte.',
  },
  {
    id: '15',
    title: 'Delírios',
    artist: 'Devaneios',
    album: 'Single',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Delírios.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Em seus delírios de amor.',
  },
  {
    id: '16',
    title: 'Dona do Meu Pensamento',
    artist: 'Onze:20',
    album: 'Vida Loka',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Dona do Meu Pensamento.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Você é a dona dos meus pensamentos.',
  },
  {
    id: '17',
    title: 'É Você - 2004 Digital Remaster',
    artist: 'Tribalistas',
    album: 'Tribalistas',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] É Você - 2004 Digital Remaster.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'É você, só você.',
  },
  {
    id: '18',
    title: 'Essa Eu Fiz Pro Nosso Amor',
    artist: 'Jão',
    album: 'Lobos',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Essa Eu Fiz Pro Nosso Amor.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Uma canção para o nosso amor.',
  },
  {
    id: '19',
    title: 'Eternamente',
    artist: 'Belo',
    album: 'Belo',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Eternamente.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Eternamente em meu coração.',
  },
  {
    id: '20',
    title: 'Eu Amo Você',
    artist: 'Tim Maia',
    album: 'Tim Maia',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Eu Amo Você.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Simplesmente, eu amo você.',
  },
  {
    id: '21',
    title: 'Gostar Só Dela',
    artist: 'Jão',
    album: 'Anti-Herói',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Gostar Só Dela.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'É sobre gostar só de você.',
  },
  {
    id: '22',
    title: 'Grão de Areia',
    artist: 'Rubel',
    album: 'Casas',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Grão de Areia.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Como um grão de areia no universo.',
  },
  {
    id: '23',
    title: 'Lisboa',
    artist: 'Anavitória',
    album: 'O Tempo É Agora',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Lisboa.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Uma viagem de amor.',
  },
  {
    id: '24',
    title: 'Mania De Você',
    artist: 'Rita Lee',
    album: 'Rita Lee',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Mania De Você.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Essa nossa mania de ser um do outro.',
  },
  {
    id: '25',
    title: 'Me Encontra',
    artist: 'Charlie Brown Jr.',
    album: 'Camisa 10 Joga Bola Até na Chuva',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Me Encontra.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Me encontra em algum lugar.',
  },
  {
    id: '26',
    title: 'Me Namora',
    artist: 'Edu Ribeiro',
    album: 'Ao Vivo',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Me Namora.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'O pedido que mudou tudo.',
  },
  {
    id: '27',
    title: 'My Kind of Woman',
    artist: 'Mac DeMarco',
    album: '2',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] My Kind of Woman.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Você é o meu tipo de mulher.',
  },
  {
    id: '28',
    title: 'Não Quero Dinheiro (Só Quero Amar)',
    artist: 'Tim Maia',
    album: 'Tim Maia',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Não Quero Dinheiro (Só Quero Amar).mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'O que importa é o nosso amor.',
  },
  {
    id: '29',
    title: 'O Vagabundo e a Dama',
    artist: 'Oriente',
    album: 'Yin Yang',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] O Vagabundo e a Dama.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Nossa história de amor improvável.',
  },
  {
    id: '30',
    title: 'Oceano',
    artist: 'Djavan',
    album: 'Djavan',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Oceano.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Um amor profundo como o oceano.',
  },
  {
    id: '31',
    title: 'Os Anjos Cantam',
    artist: 'Jorge & Mateus',
    album: 'Os Anjos Cantam',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Os Anjos Cantam.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Os anjos cantam nosso amor.',
  },
  {
    id: '32',
    title: 'Palavras No Corpo',
    artist: 'Silva',
    album: 'Silva Canta Marisa',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Palavras No Corpo.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Quando as palavras tocam a alma.',
  },
  {
    id: '33',
    title: 'Partilhar',
    artist: 'Rubel',
    album: 'Casas',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Partilhar.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'A alegria de partilhar a vida com você.',
  },
  {
    id: '34',
    title: 'Planos',
    artist: 'Vitor Kley',
    album: 'A Bolha',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Planos.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Nossos planos para o futuro.',
  },
  {
    id: '35',
    title: 'Pra Você Guardei O Amor',
    artist: 'Nando Reis',
    album: 'Drês',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Pra Você Guardei O Amor.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Todo o meu amor é seu.',
  },
  {
    id: '36',
    title: 'Pra Você',
    artist: 'Onze:20',
    album: 'Pra Você',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Pra Você.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Tudo de bom, pra você.',
  },
  {
    id: '38',
    title: 'Rosas e Rimas',
    artist: 'Lagum',
    album: 'Coisas da Geração',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Rosas e Rimas.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Nosso amor em forma de poesia.',
  },
  {
    id: '39',
    title: 'Sunshine',
    artist: 'Los Sebosos Postizos',
    album: 'Los Sebosos Postizos',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Sunshine.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Você é meu raio de sol.',
  },
  {
    id: '40',
    title: 'Tangerina - Ao Vivo',
    artist: 'Tiago Iorc',
    album: 'Acústico MTV',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Tangerina - Ao Vivo.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Doce como tangerina.',
  },
  {
    id: '41',
    title: 'Te Amar Demais',
    artist: 'Sodré',
    album: 'Single',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Te Amar Demais.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'É te amar demais.',
  },
  {
    id: '42',
    title: 'Última Noite',
    artist: 'Jão',
    album: 'Pirata',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Última Noite.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Como se fosse a última noite.',
  },
  {
    id: '43',
    title: 'Um Amor Puro',
    artist: 'Djavan',
    album: 'Malásia',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Um Amor Puro.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'O nosso amor puro.',
  },
  {
    id: '44',
    title: 'Vem Ser Minha',
    artist: 'Onze:20',
    album: 'A Nossa Barraca',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Vem Ser Minha.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Vem ser minha, pra sempre.',
  },
  {
    id: '45',
    title: 'Vilarejo',
    artist: 'Marisa Monte',
    album: 'Infinito Particular',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Vilarejo.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Nosso pequeno vilarejo de amor.',
  },
  {
    id: '46',
    title: 'Xuxuzinho',
    artist: 'Gilsons',
    album: 'Pra Gente Acordar',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] Xuxuzinho.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Meu xuxuzinho.',
  },
  {
    id: '47',
    title: 'My Kind of Woman',
    artist: 'Mac DeMarco',
    album: '2',
    src: '/music/playlist/[SPOTDOWNLOADER.COM] My Kind of Woman.mp3',
    cover: '/images/music-covers/default.jpg',
    duration: 190,
    description: 'Você é meu tipo de mulher.',
  }
];

// Playlist principal
export const mainPlaylist: Playlist = {
  id: 'nossa-playlist',
  name: 'Nossa Playlist do Coração 💕',
  tracks: musicTracks,
  isActive: true,
};

// Data de início do relacionamento
export const relationshipStartDate = '2024-12-15'; // Você pode ajustar esta data

// Cartinhas de amor
export const loveLetters: Letter[] = [
  {
    id: '1',
    type: 'love',
    title: ' Meu Coração É Seu',
    content: `Ainda existe alguma dúvida?

Meu amor, desde o dia em que eu te conheci, uma coisa posso afirmar sem medo, o meu coração é teu, e apenas teu.

Não há mais ninguém no mundo que tenha feito meu coração sorrir tanto quanto você fez. Tenho tanto orgulho de ser teu namorado, amo ficar ao seu lado, agarradinho, poder te chamar de minha, viver essa vida "sombria" em paz ao seu ladinho.

Obrigado por todas as coisas que já vivemos juntos, é uma honra dividir e compartilhar a vida com você, e mesmo se eu não quisesse, eu não poderia escolher outra coisa, porque meu coração é seu.`,
    date: '2024-12-01',
    envelope: {
      color: '#e94560',
      seal: '🍒'
    },
    availableAt: '2025-06-23T21:12:24.000Z'
  },
  {
    id: '2',
    type: 'memory',
    title: 'O Que Sinto Por Você',
    content: `O que sinto por você é muito mais do que algo passageiro, algo momentâneo. É um sentimento muito complexo e pronfundo, cheio de desejos, emoções, lembranças. Não é tão simples quanto olhar nos teus olhos e dizer que te amo, até eu às vezes não sei explicar o que eu sinto por você, porque a cada dia que passa eu acabo redescobrindo esse sentimento, de tal forma que eu não consigo nem imaginar o que seria minha vida sem você. Eu te quero, te desejo, te almejo, e espero que esteja ao meu lado por toda a minha vida, pois não sei mais viver sem você, minha amada.`,
    date: '2024-10-20',
    envelope: {
      color: '#f5d76e',
      seal: '🌟'
    },
    availableAt: '2025-06-24T21:12:24.000Z'
  },
  {
    id: '3',
    type: 'future',
    title: 'Por Que Te Amo?',
    content: `A resposta pra essa pergunta parece ser meio difícil, e realmente é. Poderia citar uma lista de mil coisas pelas quais eu te amo. Te amar parece algo que eu sempre fui predestinado a fazer, sinto que nasci pra estar contigo, viver essa vida louca ao teu lado, poder te chamar de esposa um dia. Eu te amo por estar sempre comigo, nos bons e nos piores momentos, por me apoiar, por ser tão ótima e engraçada ao ponto de conseguir melhorar os meus dias, não importando o quão ruins eles possam estar sendo. Eu te amo pelas suas piadas bobas e reações inusitadas, continue sendo você, e eu continuarei te amando. Me sinto até o Will Traynor, minha vida só passou a fazer sentido ao seu lado, e eu não quero mais ser como eu era antes de você.`,
    date: '2024-11-15',
    envelope: {
      color: '#60a5fa',
      seal: '🐋'
    },
    availableAt: '2025-06-25T21:12:24.000Z'
  },
  {
    id: '4',
    type: 'special',
    title: 'Nossos Sonhos Juntos',
    content: `Quando olho pro futuro só enxergo você, você é o meu maior sonho, tudo que eu almejo eu me imagino alcançado ao teu lado, me sinto confortavel o suficiente para escolher estar contigo pro resto da vida e eu não tenho dúvidas quanto a isso. Não sei se você sabe, mas é claro que eu sonho e penso em você barrigudinha, gerando nossa maior felicidade. Com certeza contarei a Aurora e Thomas o quão a mãe deles foi uma namorada incrivel, meio doidinha, mas incrivel. Prometo te fazer muito mais feliz do que um dia já fiz, ainda tenho muito a te oferecer, e espero que continue me concendo a oportinidade de mostrar isso a você todos os dias.
    
    PS: Prometo que quando casarmos teremos um cachorro, três gatos, um papagaio, dois coelhos (um preto e um branco) e um casal de calopsita.
    
    Eu te amo 🤍`,
    date: '2024-12-10',
    envelope: {
      color: '#10b981',
      seal: '🍀'
    },
    availableAt: '2025-06-26T21:12:24.000Z'
  }
];

// Timeline do relacionamento
export const timelineEvents: TimelineEvent[] = [
  {
    id: '1',
    title: 'Primeiro Encontro',
    description: 'O dia em que nossas vidas se cruzaram e tudo começou ✨',
    date: '2024-10-15',
    type: 'meeting',
    icon: '💕',
    location: 'Café do Centro',
    photos: ['/images/timeline/primeiro-encontro.jpg']
  },
  {
    id: '2',
    title: 'Primeiro Beijo',
    description: 'O momento mágico que selou nosso destino juntos 💋',
    date: '2024-10-22',
    type: 'milestone',
    icon: '💋',
    location: 'Parque da Cidade'
  },
  {
    id: '3',
    title: 'Namoro Oficial',
    description: 'O "sim" mais bonito que já ouvi na vida! Agora somos oficialmente nós dois contra o mundo 👫',
    date: '2024-11-01',
    type: 'milestone',
    icon: '💑',
    location: 'Nossa mesa favorita no restaurante'
  },
  {
    id: '4',
    title: 'Primeira Viagem Juntos',
    description: 'Nossa primeira aventura como casal! Três dias de pura felicidade e descobertas 🏖️',
    date: '2024-11-20',
    type: 'travel',
    icon: '✈️',
    location: 'Praia do Paraíso',
    photos: ['/images/timeline/primeira-viagem.jpg']
  },
  {
    id: '5',
    title: 'Natal Juntos',
    description: 'Nosso primeiro Natal como casal! A magia da época mais especial do ano ficou ainda mais bonita ao seu lado 🎄',
    date: '2024-12-25',
    type: 'special',
    icon: '🎄',
    location: 'Casa da Família'
  },
  {
    id: '6',
    title: 'Museu Flutuante',
    description: 'Criei este museu especial para você, para guardar para sempre todos os nossos momentos mais preciosos 💖',
    date: '2025-01-19',
    type: 'special',
    icon: '🏛️',
    location: 'No meu coração e agora na internet!'
  }
];

// Frases românticas para elementos aleatórios
export const romanticQuotes = [
  "Você é a música mais bonita que meu coração já ouviu 🎵",
  "Em cada foto nossa, vejo nossa história se escrevendo 📸",
  "Cada dia com você é uma nova página no nosso livro de amor 📖",
  "Você transformou minha vida em uma sinfonia de alegria 🎼",
  "Nosso amor é a obra de arte mais linda do mundo 🎨",
  "Com você, cada momento é uma memória preciosa ✨",
]; 